# Generated by Django 4.2.7 on 2024-06-18 23:12

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('admin_role', models.CharField(choices=[('R', 'Register'), ('S', 'System Admin')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('credit_hour', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(35)])),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('CGPA', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(Decimal('4.00')), django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('join_year', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('grade', models.CharField(choices=[('A', 'Excellent'), ('B', 'Very Good'), ('C', 'Good'), ('D', 'Pass'), ('F', 'Fail')], max_length=1)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='enrollment', serialize=False, to='school.course')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='school.department')),
            ],
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], max_length=1)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(related_name='required_courses', to='school.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='school.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment',
            field=models.ManyToManyField(to='school.enrollment'),
        ),
        migrations.AddField(
            model_name='student',
            name='programs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.program'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('office_number', models.PositiveSmallIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_department', to='school.department')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.enrollment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
